services:
  _defaults:
    public: true
    autowire: true
    autoconfigure: true

  LearningManagementFrameworkBundle\Controller\:
    resource: '../../Controller'
    public: true
    tags: ['controller.service_arguments']

  LearningManagementFrameworkBundle\Tools\Installer:
    public: true
    arguments:
      $bundle: "@=service('kernel').getBundle('PimcoreLearningManagementFrameworkBundle')"

  LearningManagementFrameworkBundle\Helper\ExamHelper:
    arguments:
      $defaultStudentClass: '%pimcore_learning_management_framework.student_class%'