services:
  _defaults:
    public: true
    autowire: true
    autoconfigure: true

  LearningManagementFrameworkBundle\Tools\Installer:
    public: true
    arguments:
      $bundle: "@=service('kernel').getBundle('PimcoreLearningManagementFrameworkBundle')"

  LearningManagementFrameworkBundle\Helper\ExamHelper: ~